logging:
  project_name: "EFVFL"
  experiment_name: "cifar10-cvfl-0.01k"

data:
  module_path: "data.cifar10"
  module_name: "CIFAR10DataModule"
  params:
    data_dir: "../data"
    num_workers: 8
    batch_size: 128

model:
  module_path: "models.cifar10_model"
  module_name: "ResNetSplitNN"
  params:
    num_clients: 4
    cut_size: 256
    aggregation_mechanism: "mean"
    num_classes: 10
    private_labels: false
    optimizer: "sgd"
    lr: 0.01
    momentum: 0.5
    weight_decay: 0.008
    scheduler: "cosine_annealing_lr"
    eta_min_ratio: 0.01
    compression_type: "direct"
    compressor: "topk"
    compression_parameter: 0.01
    compute_grad_sqd_norm: false

trainer:
  max_epochs: 100
