logging:
  project_name: "EFVFL"
  experiment_name: "cifar10-efvfl-5b"

data:
  module_path: "data.cifar10"
  module_name: "CIFAR10DataModule"
  params:
    data_dir: "../data"
    num_workers: 8
    batch_size: 128

model:
  module_path: "models.cifar10_model"
  module_name: "ResNetSplitNN"
  params:
    num_clients: 4
    cut_size: 16
    aggregation_mechanism: "mean"
    num_classes: 10
    private_labels: false
    optimizer: "sgd"
    lr: 0.01
    momentum: 0.0
    weight_decay: 0.01
    scheduler: null
    eta_min_ratio: null
    compression_type: "ef"
    compressor: "qsgd"
    compression_parameter: 5
    compute_grad_sqd_norm: false

trainer:
  max_epochs: 100
