seed: 42

logging:
  project_name: "EFVFL"
  experiment_name: "test"

data:
  module_path: "data.mnist"  # Path to the new MNIST data module
  module_name: "MNISTDataModule"         # Name of the data module class
  params:                                # Parameters for the data module class
    data_dir: "../data"
    batch_size: 64
    num_workers: 4
    val_split: 0.2

model:
  module_path: "models.mnist_model"       # Path to the new model module
  module_name: "SimpleNN"                 # Name of the model class
  params:                                 # Parameters for the model class
    input_size: 784                       # 28x28 flattened MNIST images
    hidden_size: 128                      # Size of the hidden layer
    output_size: 10                       # Number of classes in MNIST (0-9)
    learning_rate: 0.001                  # Learning rate for optimizer

trainer:
  max_epochs: 1 # 100
  gpus: [3]
