logging:
  project_name: "EFVFL"
  experiment_name: "mnist-fullbatch-cvfl-0.1k"

data:
  module_path: "data.mnist"
  module_name: "MNISTDataModule"
  params:
    data_dir: "../data"
    num_workers: 4

model:
  module_path: "models.mnist_model"
  module_name: "ShallowSplitNN"
  params:
    num_clients: 4
    input_size: 784
    cut_size: 128
    aggregation_mechanism: "sum"
    num_classes: 10
    lr: 1.0
    momentum: 0.0
    compression_type: "direct"
    compressor: "topk"
    compression_parameter: 0.1
    compute_grad_sqd_norm: true

trainer:
  max_epochs: 100
