seed: [0] # [0, 1, 2, 3, 4]

logging:
  project_name: "EFVFL"
  experiment_name: "mnist-fullbatch-efvfl-0.1k"

data:
  module_path: "data.mnist"
  module_name: "MNISTDataModule"
  params:
    data_dir: "../data"
    num_workers: 4
    val_split: 0.1

model:
  module_path: "models.mnist_model"
  module_name: "ShallowSplitNN"
  params:
    num_clients: 4
    input_size: 784
    cut_size: 16
    aggregation_mechanism: "conc"
    num_classes: 10
    lr: 1.0
    momentum: 0.0
    compression_type: "ef"
    compressor: "topk"
    compression_parameter: 0.1

trainer:
  max_epochs: 100
  gpus: [3]
