logging:
  project_name: "EFVFL"
  experiment_name: "mnist-fullbatch-efvfl-5b"

data:
  module_path: "data.mnist"
  module_name: "MNISTDataModule"
  params:
    data_dir: "../data"
    batch_size: null
    num_workers: 4

model:
  module_path: "models.mnist_model"
  module_name: "ShallowSplitNN"
  params:
    input_size: 784
    num_clients: 4
    cut_size: 128
    aggregation_mechanism: "sum"
    num_classes: 10
    private_labels: false
    lr: 128.0
    momentum: 0.0
    weight_decay: 0.0
    compression_type: "ef"
    compressor: "qsgd"
    compression_parameter: 5
    compute_grad_sqd_norm: true

trainer:
  max_epochs: 100
